from setuptools import setup, find_packages
setup(name='lodstats-plugin-to-file',
      version='1.0.0',
      author = 'Ivan Ermilov',
      author_email = 'iermilov@informatik.uni-leizpig.de',
      url = 'https://github.com/earthquakesan/LODStats-plugin-to-file',
      download_url = 'https://github.com/earthquakesan/LODStats-plugin-to-file',
      description = 'Plugin for dumping RDFStat object to the pickle',
      long_description = """
          """,
      classifiers = ['Development Status :: 3 - Alpha',
                     'License :: OSI Approved :: GNU General Public License (GPL)',
                     'Programming Language :: Python',
                     'Intended Audience :: Information Technology',
                     'Intended Audience :: Science/Research',
                     'Environment :: Console',
                     'Topic :: Software Development :: Libraries :: Python Modules',
                     'Topic :: Scientific/Engineering :: Information Analysis',
                     'Topic :: Internet :: WWW/HTTP',
                     'Topic :: Utilities',
                    ],
      packages=find_packages(),
      scripts=[''],
      package_data={'lodstats': ['rdf/*.rdf']},
      include_package_data=True,
      install_requires = ['lodstats'],
      )
